"use client";
import DesignReview from './design-review';
import {drawingKey,type PavilionDrawings} from './review-drawings';
import type {QuoteCustomer} from '@/lib/pavilion-commerce';
import {FurnitureControls} from './furniture-controls';
import {readDraft,writeDraft} from './local-draft';
import {QuoteCheckout,PaymentReturn} from "./quote-checkout";
import {decodeDesignHash} from "@/lib/pavilion-commerce";
import {TIMBER_SURFACES} from "./timber-surface";
import {lazy,Suspense,useCallback,useEffect,useRef,useState,Component,type Dispatch,type SetStateAction,type ReactNode} from 'react';
import {ArrowLeft,ArrowRight,Check,House,Layers,Maximize,Paintbrush,RotateCcw,Ruler,TreePine,Undo2,Redo2,Box,Armchair,Settings2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Switch} from '@/components/ui/switch';
import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Tooltip,TooltipContent,TooltipProvider,TooltipTrigger} from '@/components/ui/tooltip';
import {Toaster,toast} from 'sonner';
import {requiresTrussPlates,availableHeights,availableTrusses,expandedFrame,fitSize,trussPreviewPath} from '@/lib/pavilion-layout';
import {CUSTOMER_PAVILION_SIZES,TRUSS_STYLES,WOOD_FINISHES,ROOF_MATERIALS,ROOF_MATERIAL_TYPES,RAFTER_TAILS,type PavilionConfig} from '@/lib/pavilion-config';
import {computeQuote,selectionFromConfig,fmtUSD,snowOptionQuote} from '@/lib/pricing/engine';
import {usePricing} from './published-settings';
import catalog from '@/lib/pricing/catalog.json';
import type {PricingDoc} from '@/lib/pricing/types';
import {initialDesign,designSchema,stains,stainName,type Design} from './designer-model';
import {useDesignHistory} from './use-design-history';
import SavedDesigns from './saved-designs';
import {usePavilionTools} from './use-webmcp';
import type {ViewPreset} from './Scene';
const ReferenceScene=lazy(()=>import('./reference-scene').then(m=>({default:m.ReferenceScene})));
const steps=[{label:'Style & size',title:'Build your pavilion',description:'Choose your footprint and timber frame.',icon:House},{label:'Timber finish',title:'A finish with character',description:'Eastern White Pine, finished your way.',icon:TreePine},{label:'Stain colors',title:'Make it yours',description:'Choose beam and ceiling finishes independently.',icon:Paintbrush},{label:'Roofing',title:'Complete your roof',description:'Compare materials and colors in 3D.',icon:Layers},{label:'Details',title:'The finishing touches',description:'Tail profiles, trim, and a view of your space.',icon:Settings2},{label:'Review',title:'Your KSM pavilion',description:'Review the details and save your design.',icon:Check}];
class SceneBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true}}render(){return this.state.failed?<div className="scene-loading"><Box size={32}/><h2>The 3D view couldn’t load</h2><p>Your design selections are still available.</p><Button onClick={()=>this.setState({failed:false})}>Retry 3D view</Button></div>:this.props.children}}
function Tool({label,children,onClick,disabled=false}:{label:string;children:ReactNode;onClick:()=>void;disabled?:boolean}){return <Tooltip><TooltipTrigger asChild><button className="icon-button" aria-label={label} onClick={onClick} disabled={disabled}>{children}</button></TooltipTrigger><TooltipContent>{label}</TooltipContent></Tooltip>}
function Toggle({label,hint,checked,onChange,disabled=false}:{label:string;hint?:string;checked:boolean;onChange:(v:boolean)=>void;disabled?:boolean}){return <label className="toggle-row"><span><strong>{label}</strong>{hint&&<small>{hint}</small>}</span><Switch checked={checked} onCheckedChange={onChange} aria-label={label} disabled={disabled}/></label>}
function Pick({label,value,choices,onChange}:{label:string;value:string;choices:{id:string;name:string}[];onChange:(v:string)=>void}){return <label className="field-label">{label}<Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{choices.map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></label>}
export default function Designer(){
 const pricing=usePricing();
 const {value:design,set:setRawDesign,undo,redo,canUndo,canRedo}=useDesignHistory<Design>(initialDesign),config=design.config;
 const setDesign:Dispatch<SetStateAction<Design>>=useCallback(value=>setRawDesign(d=>designSchema.parse(typeof value==='function'?value(d):value)),[setRawDesign]);
 const [draftReady,setDraftReady]=useState(false);
 const draftWarning=useRef(false);
 const [reviewOpen,setReviewOpen]=useState(false);
 const [customer,setCustomer]=useState<QuoteCustomer>({name:'',email:'',phone:'',fulfillment:'pickup',address:'',notes:'',sendCopyToCustomer:true});
 const [projectName,setProjectName]=useState('My KSM pavilion');
 const [reviewDrawings,setReviewDrawings]=useState<{key:string;drawings:PavilionDrawings|null}|null>(null);
 const acceptDrawings=useCallback((key:string,drawings:PavilionDrawings|null)=>setReviewDrawings({key,drawings}),[]);
 const [quoteOpen,setQuoteOpen]=useState(false),[quoteIntent,setQuoteIntent]=useState<'quote'|'order'>('quote');
 const [step,setStep]=useState(0),[view,setView]=useState<ViewPreset>('3d'),[roofVisible,setRoofVisible]=useState(true),[dimensions,setDimensions]=useState(false),[measure,setMeasure]=useState(false),[pad,setPad]=useState(true),[garden,setGarden]=useState(true),[sceneTick,setSceneTick]=useState(0),[client,setClient]=useState(false),[saveOpen,setSaveOpen]=useState(false),[mobile,setMobile]=useState('design');
 const viewerRef=useRef<HTMLElement>(null),panelRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{
  setClient(true);
  try {
   let restored:Design|null=null;
   try {restored=decodeDesignHash(window.location.hash);if(restored){toast.success('Shared pavilion opened.');window.history.replaceState(null,'',window.location.pathname+window.location.search)}}catch{toast.error('This design link could not be opened.')}
   if(!restored&&new URLSearchParams(window.location.search).get('checkout')==='return'){
    try {const pending=JSON.parse(sessionStorage.getItem('ksm-pending-payment')||'null');const result=designSchema.safeParse(pending?.design);if(result.success)restored=result.data}catch{}
   }
   if(!restored){try {restored=readDraft(localStorage);if(restored)toast.success('Your last pavilion draft was restored.')}catch{}}
   if(restored)setDesign(restored);
  }finally{setDraftReady(true)}
 },[setDesign]);
 useEffect(()=>{if(!draftReady)return;try{writeDraft(localStorage,design)}catch{if(!draftWarning.current){toast.info('Automatic saving is unavailable. Go to Review and choose Save to my designs to keep your work.');draftWarning.current=true}}},[design,draftReady]);
 useEffect(()=>{panelRef.current?.scrollTo({top:0})},[step]);
 const update=<K extends keyof PavilionConfig>(key:K,value:PavilionConfig[K])=>setDesign(d=>({...d,config:{...d.config,[key]:value}}));
 const roof=ROOF_MATERIALS.find(r=>r.id===config.roofId)!,truss=TRUSS_STYLES.find(t=>t.id===config.truss)!;
 const quote=computeQuote(selectionFromConfig(config,{beamStained:design.tableStain!==null,deckStained:design.deckStain!==null}),pricing);
 const pending=quote.callForPricing;
 const basePending=pending.some(label=>label.startsWith('Base price'));
 const snowHint=(key:'snowGuards'|'snowRail')=>{const option=snowOptionQuote(pricing,config,key);return `${option.amount===null?'Price pending':`+${fmtUSD(option.amount)}`} · ${option.detail} · both roof slopes`};
 const specs:[string,string][]=[['Pavilion',truss.name],['Size',`${config.width}′ × ${config.length}′`],['Post height',`${config.height}′`],['Timber finish',WOOD_FINISHES.find(w=>w.id===config.woodId)?.name||''],['Beam stain',stainName(design.tableStain)],['Ceiling stain',stainName(design.deckStain)],['Roof',`${ROOF_MATERIAL_TYPES.find(t=>t.id===roof.type)?.name} · ${roof.name}`],['Rafter tails',config.rafterTail==='scroll'?'Scroll cut':'Standard'],['Decorative plates',config.trussPlates?'Included':'None'],['Gable faceboard',config.gableFascia?'Included':'None'],['Gable overhang',config.gableOverhang?'Included':'None'],['Rear truss',config.hideBackTruss?'Omitted':'Included'],['Snow guards',config.snowGuards?'Included':'None'],['Snow rail',config.snowRail?'Included':'None']];
 function openQuote(intent:'quote'|'order'){setQuoteIntent(intent);setQuoteOpen(true)}
 function capture(){try{return viewerRef.current?.querySelector('canvas')?.toDataURL('image/jpeg',0.72)}catch{return undefined}}
 function changeRoofType(type:string){const match=ROOF_MATERIALS.find(r=>r.type===type&&r.name===roof.name)||ROOF_MATERIALS.find(r=>r.type===type)!;setDesign(d=>({...d,config:{...d.config,roofId:match.id,snowGuards:type!=='shingle'?d.config.snowGuards:false,snowRail:type==='shingle'?false:d.config.snowRail}}))}
 usePavilionTools(design,setDesign,quote.total,pending);
 return <TooltipProvider><main className="ksm-designer"><Toaster richColors position="top-center"/>
 <header className="app-header"><div className="brand-lockup"><img src="/brand/ksm-logo.png" alt="KSM Log Homes Co."/><div><span className="brand-eyebrow">KSM DESIGN STUDIO</span><h1>Timber Pavilion Designer</h1></div></div><div className="header-actions"><Tool label="Undo" onClick={undo} disabled={!canUndo}><Undo2 size={18}/></Tool><Tool label="Redo" onClick={redo} disabled={!canRedo}><Redo2 size={18}/></Tool></div></header>
 <Tabs className="step-tabs" value={String(step)} onValueChange={v=>{if(v==='5')setReviewOpen(true);else setStep(Number(v))}}><TabsList className="step-list">{steps.map((s,i)=><TabsTrigger value={String(i)} key={s.label} className="step-trigger"><span className="step-number">{i<step?<Check size={15}/>:String(i+1).padStart(2,'0')}</span><s.icon size={18}/><span>{s.label}</span></TabsTrigger>)}</TabsList></Tabs>
 <div className="mobile-switch"><button className={mobile==='design'?'active':''} onClick={()=>setMobile('design')}>Design options</button><button className={mobile==='model'?'active':''} onClick={()=>setMobile('model')}>3D pavilion</button></div>
 <div className="workspace" data-mobile={mobile}><section className="viewer" ref={viewerRef} aria-label="Interactive pavilion preview"><div className="scene-container"><SceneBoundary>{client?<Suspense fallback={<div className="scene-loading"><Box size={35}/><h2>Building your pavilion</h2><p>Loading KSM timber models…</p></div>}><ReferenceScene key={sceneTick} config={config} view={view} showRoof={reviewOpen||roofVisible} showPad={pad} showBackyard={garden} furnitureLayout={design.furnitureLayout} tv={design.tv} showTable={design.furnitureLayout.picnic.enabled} showSectional={design.furnitureLayout.sectional.enabled} showEgg={design.furnitureLayout.grill.enabled} showTv={design.tv.enabled} showDining={design.furnitureLayout.dining.enabled} showPatio={design.furnitureLayout.patio.enabled} tableStain={design.tableStain} deckStain={design.deckStain} measureEnabled={measure} showDimensions={dimensions}/></Suspense>:<div className="scene-loading">Loading pavilion…</div>}</SceneBoundary></div>
 <div className="model-label"><TreePine size={24}/><div><strong>{truss.name}</strong><span>{config.width}′ × {config.length}′ · {config.height}′ posts</span></div></div><div className="viewer-tools" role="toolbar" aria-label="3D preview controls" aria-orientation="vertical"><Tool label="Undo" onClick={undo} disabled={!canUndo}><Undo2 size={19}/></Tool><Tool label="Redo" onClick={redo} disabled={!canRedo}><Redo2 size={19}/></Tool><span className="viewer-tool-divider" aria-hidden="true"/><Tool label="Reset camera" onClick={()=>{setView('3d');setSceneTick(t=>t+1)}}><RotateCcw size={18}/></Tool><Tool label="Fullscreen" onClick={()=>{if(document.fullscreenElement)document.exitFullscreen();else viewerRef.current?.requestFullscreen?.().catch(()=>toast.error('Fullscreen is not available on this device.'))}}><Maximize size={18}/></Tool></div>
 {dimensions&&<div className="dimensions-badge"><Ruler size={17}/>{config.width}′ width × {config.length}′ length × {config.height}′ post height</div>}
 <div className="viewer-bottom"><div className="view-presets">{([{id:'3d',label:'Perspective'},{id:'side',label:'Side'},{id:'top',label:'Top'}] as const).map(v=><button key={v.id} className={view===v.id?'active':''} onClick={()=>setView(v.id)}>{v.label}</button>)}</div><div className="view-switches"><label><Ruler size={16}/> Dimensions<Switch checked={dimensions} onCheckedChange={setDimensions} aria-label="Show dimensions"/></label><label><Layers size={16}/> Roof<Switch checked={roofVisible} onCheckedChange={setRoofVisible} aria-label="Show roof"/></label></div></div><p className="viewer-help">Drag to rotate <span>·</span> Scroll or pinch to zoom <span>·</span> Right-drag to pan</p></section>
 <aside className="inspector"><div className="inspector-heading"><span className="eyebrow">STEP {step+1} OF {steps.length}</span><h2>{steps[step].title}</h2><p>{steps[step].description}</p></div><div className="panel-scroll" ref={panelRef}>
 {step===0&&<><section className="dimension-card"><div className="section-label"><Ruler size={18}/><h3>Pavilion dimensions</h3></div><div className="dimension-fields"><Pick label="Width" value={String(config.width)} choices={[...new Set(CUSTOMER_PAVILION_SIZES.map(s=>s.width))].map(w=>({id:String(w),name:w+' feet'}))} onChange={v=>{const width=Number(v);const length=CUSTOMER_PAVILION_SIZES.some(s=>s.width===width&&s.length===config.length)?config.length:CUSTOMER_PAVILION_SIZES.find(s=>s.width===width)!.length;setDesign(d=>({...d,config:fitSize(d.config,width,length)}))}}/><span>×</span><Pick label="Length" value={String(config.length)} choices={CUSTOMER_PAVILION_SIZES.filter(s=>s.width===config.width).map(s=>({id:String(s.length),name:s.length+' feet'}))} onChange={v=>setDesign(d=>({...d,config:fitSize(d.config,d.config.width,Number(v))}))}/></div><div className="area-note">{config.width*config.length} sq. ft. footprint{expandedFrame(config.width,config.length)?.packageNote&&<> · {expandedFrame(config.width,config.length)!.packageNote}</>}</div><Pick label="Post height" value={String(config.height)} choices={availableHeights(config.width,config.length).map(h=>({id:String(h),name:h+' feet'}))} onChange={v=>update('height',Number(v))}/></section><h3 className="section-title">Truss style</h3><div className="option-stack">{TRUSS_STYLES.filter(t=>availableTrusses(config.width,config.length).some(id=>id===t.id)).map(t=><button className={'style-card '+(config.truss===t.id?'selected':'')} aria-pressed={config.truss===t.id} key={t.id} onClick={()=>update('truss',t.id)}><span className="truss-symbol"><img src={trussPreviewPath(config.width,config.length,t.id)} alt="" width={120} height={85}/></span><span><strong>{t.name}</strong><small>{t.id==='king'?'Classic center-post frame':t.id==='arch'?'Curved timbers and open detail':'Hammer beam construction'}</small></span><span className="choice-check">{config.truss===t.id&&<Check size={16}/>}</span></button>)}</div><p className="panel-note">Need a wider pavilion? KSM can help with a custom quote.</p></>}
 {step===1&&<><div className="finish-grid">{WOOD_FINISHES.map(f=><button className={'finish-card '+(config.woodId===f.id?'selected':'')} aria-pressed={config.woodId===f.id} key={f.id} onClick={()=>update('woodId',f.id)}><img src={`/finish-samples/${f.id}.webp`} alt={f.name+' timber texture'}/><span>{f.name}{config.woodId===f.id&&<Check size={17}/>}</span><small>{TIMBER_SURFACES[f.id]?.description}</small></button>)}</div><p className="panel-note">All structural timber is Eastern White Pine. Each finish changes the surface in 3D. Zoom in to compare the grain and tool marks.</p></>}
 {step===2&&<>{(['tableStain','deckStain'] as const).map(key=><section className="stain-section" key={key}><div className="section-title-row"><h3>{key==='tableStain'?'Beams & posts':'Ceiling boards'}</h3><span>{stainName(design[key])}</span></div><div className="swatch-grid">{stains.map(s=><button key={s.name} className={'swatch-option '+(design[key]===s.hex?'selected':'')} onClick={()=>setDesign(d=>({...d,[key]:s.hex}))} aria-label={(key==='tableStain'?'Beam stain: ':'Ceiling stain: ')+s.name} title={s.name}><span style={{background:s.hex||'linear-gradient(100deg,#b98a42,#e3bd77,#c89e53)'}}>{design[key]===s.hex&&<Check size={19} style={{color:s.hex&&['#15120e','#5a3a25','#5e4530','#6b4423','#8a4a2a'].includes(s.hex)?'white':'#19332c'}}/>}</span><small>{s.name}</small></button>)}</div></section>)}<Button variant="outline" className="full-width" onClick={()=>setDesign(d=>({...d,deckStain:d.tableStain}))}>Match ceiling to beam stain</Button><p className="panel-note">Screen colors are a guide. Confirm your finish with a KSM stain sample.</p></>}
 {step===3&&<><Pick label="Roof material" value={roof.type} onChange={changeRoofType} choices={ROOF_MATERIAL_TYPES}/><div className="section-title-row"><h3>Roof color</h3><span>{roof.name}</span></div><div className="swatch-grid">{ROOF_MATERIALS.filter(r=>r.type===roof.type).map(r=><button key={r.id} className={'swatch-option '+(r.id===roof.id?'selected':'')} onClick={()=>update('roofId',r.id)} title={r.name} aria-label={'Roof color: '+r.name}><span style={{background:r.hex}}>{r.id===roof.id&&<Check size={19} color="white" style={{filter:'drop-shadow(0 1px 1px #000)'}}/>}</span><small>{r.name}</small></button>)}</div></>}
 {step===4&&<><h3 className="section-title">Timber & roof details</h3><Pick label="Rafter tail" value={config.rafterTail} onChange={v=>update('rafterTail',v as PavilionConfig['rafterTail'])} choices={RAFTER_TAILS}/><Toggle label="Truss plate package" hint={requiresTrussPlates(config.width)?"Required for pavilions wider than 16′.":undefined} disabled={requiresTrussPlates(config.width)} checked={config.trussPlates} onChange={v=>update('trussPlates',v)}/><Toggle label="Gable faceboard" checked={config.gableFascia} onChange={v=>update('gableFascia',v)}/><Toggle label="Gable overhang" checked={config.gableOverhang} onChange={v=>update('gableOverhang',v)}/><Toggle label="Omit rear truss" hint="For a pavilion positioned against a wall." checked={!!config.hideBackTruss} onChange={v=>update('hideBackTruss',v)}/>{roof.type!=='shingle'&&<section className="snow-options"><img className="snow-detail-image" src="/roof-details/snow-guards.png" alt="Close-up of staggered seam-mounted snow guards on a metal roof"/><Toggle label="Snow guards" hint={snowHint("snowGuards")} checked={config.snowGuards} onChange={v=>{setDesign(d=>({...d,config:{...d.config,snowGuards:v,snowRail:v?false:d.config.snowRail}}));if(v){setRoofVisible(true);setView('3d')}}}/><p className="panel-note">Individual guards appear in staggered rows near both eaves and match your roof color.</p><Toggle label="Snow rail" hint={snowHint("snowRail")} checked={!!config.snowRail} onChange={v=>{setDesign(d=>({...d,config:{...d.config,snowRail:v,snowGuards:v?false:d.config.snowGuards}}));if(v){setRoofVisible(true);setView('3d')}}}/></section>}<div className="section-divider"/><h3 className="section-title"><Armchair size={18}/> Visualize your space</h3><FurnitureControls design={design} onChange={setDesign}/><p className="panel-note">Furniture, the TV and the patio pad are shown for scale and are not included in the pavilion price.</p><Toggle label="Patio pad" checked={pad} onChange={setPad}/><Toggle label="Outdoor setting" checked={garden} onChange={setGarden}/><Toggle label="Measure in 3D" hint="Click two points on the model to measure." checked={measure} onChange={v=>{setMeasure(v);if(v)setMobile('model')}}/></>}

 </div><div className="panel-next"><Button variant="ghost" disabled={step===0} onClick={()=>setStep(s=>s-1)}><ArrowLeft size={16}/> Back</Button><Button onClick={()=>{if(step===4)setReviewOpen(true);else setStep(s=>s+1);setMobile('design')}}>{steps[step+1].label}<ArrowRight size={16}/></Button></div></aside></div>
 <footer className="estimate-bar"><div className="footer-design"><img src="/brand/ksm-symbol.png" alt=""/><div><strong>Your {truss.name} Pavilion</strong><span>{config.width}′ × {config.length}′ <b>·</b> {WOOD_FINISHES.find(w=>w.id===config.woodId)?.name} <b>·</b> {roof.name}</span></div></div><div className="footer-price"><div><span>{basePending?'Pavilion price':pending.length?'Priced subtotal':'Estimated total'}</span><strong>{basePending?'To be quoted':fmtUSD(quote.total)}{!basePending&&<small> USD</small>}</strong>{pending.length>0&&<small>Selected details require a quote</small>}</div><Button className="review-button" onClick={()=>setReviewOpen(true)}>Review design<ArrowRight size={18}/></Button></div></footer>
 <DesignReview open={reviewOpen} onOpenChange={setReviewOpen} design={design} specs={specs} customer={customer} setCustomer={setCustomer} projectName={projectName} setProjectName={setProjectName} onNotes={notes=>setDesign(d=>({...d,notes}))} onQuote={openQuote} onSave={()=>setSaveOpen(true)} onEdit={s=>{setStep(s);setReviewOpen(false);setMobile('design')}} onDrawings={acceptDrawings}/>
 <a className="admin-entry" href="/admin">Admin</a><PaymentReturn/><QuoteCheckout open={quoteOpen} onOpenChange={setQuoteOpen} design={design} intent={quoteIntent} capture={capture} customer={customer} setCustomer={setCustomer} projectName={projectName} setProjectName={setProjectName} onNotes={notes=>setDesign(d=>({...d,notes}))} drawings={reviewDrawings?.key===drawingKey(design)?reviewDrawings.drawings:null} specs={specs}/><SavedDesigns open={saveOpen} onOpenChange={setSaveOpen} design={design} onLoad={d=>{setDesign(d);setStep(0);setReviewOpen(false);toast.success('Saved pavilion opened.')}}/>
 </main></TooltipProvider>;
}
