"use client";
import {useEffect,useState} from 'react';
import type {Session} from '@supabase/supabase-js';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {FolderOpen,ChevronRight} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import {designSchema,type Design} from './designer-model';
type Saved={id:string;name:string;config:Design;updated_at:string};
export default function SavedDesigns({open,onOpenChange,design,onLoad}:{open:boolean;onOpenChange:(o:boolean)=>void;design:Design;onLoad:(d:Design)=>void}){
 const [session,setSession]=useState<Session|null>(null),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[signup,setSignup]=useState(false),[name,setName]=useState('My KSM pavilion'),[saved,setSaved]=useState<Saved|null>(null),[list,setList]=useState<Saved[]>([]),[loading,setLoading]=useState(false);
 useEffect(()=>{const db=supabase();let live=true;db.auth.getSession().then(({data,error})=>{if(!live)return;setSession(data.session);setReady(true);if(error)setMessage(error.message)});const {data}=db.auth.onAuthStateChange((_e,s)=>{setSession(s);setReady(true)});return()=>{live=false;data.subscription.unsubscribe()}},[]);
 useEffect(()=>{setSaved(null);setList([])},[session?.user.id]);
 async function refresh(){setLoading(true);try{const {data,error}=await supabase().from('ksm_pavilion_designs').select('id,name,config,updated_at').order('updated_at',{ascending:false}).limit(100);if(error)throw error;setList(data||[])}finally{setLoading(false)}}
 useEffect(()=>{if(open&&session)refresh().catch(e=>setMessage(e.message))},[open,session?.user.id]);
 async function authenticate(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{const db=supabase();const {data,error}=signup?await db.auth.signUp({email,password}):await db.auth.signInWithPassword({email,password});if(error)throw error;setPassword('');if(signup&&!data.session)setMessage('Check your email to confirm your account, then return to this designer and sign in.')}catch(e){setMessage(e instanceof Error?e.message:'Sign-in failed.')}finally{setBusy(false)}}
 async function save(copy=false){setBusy(true);setMessage('');try{if(!session)throw Error('Sign in to save this design.');if(!name.trim())throw Error('Give your design a name.');const parsed=designSchema.parse(design);const payload={name:name.trim(),config:parsed};const db=supabase();const result=saved&&!copy?await db.from('ksm_pavilion_designs').update(payload).eq('id',saved.id).eq('updated_at',saved.updated_at).select('id,name,config,updated_at').maybeSingle():await db.from('ksm_pavilion_designs').insert({...payload,user_id:session.user.id}).select('id,name,config,updated_at').single();if(result.error)throw result.error;if(!result.data)throw Error('This design changed on another device. Open the latest version or save a copy.');setSaved(result.data);await refresh();setMessage('Saved to your account. You can open it on another device.')}catch(e){setMessage(e instanceof Error?e.message:'Could not save. Your current design is still open.')}finally{setBusy(false)}}
 function load(row:Saved){const p=designSchema.safeParse(row.config);if(!p.success){setMessage('This saved design is not compatible with this version.');return}onLoad(p.data);setSaved(row);setName(row.name);setMessage('');onOpenChange(false)}
 async function signOut(){setBusy(true);try{const {error}=await supabase().auth.signOut();if(error)throw error;setMessage('Signed out.')}catch(e){setMessage(e instanceof Error?e.message:'Could not sign out.')}finally{setBusy(false)}}
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="saved-dialog"><DialogHeader><DialogTitle>My pavilion designs</DialogTitle><DialogDescription>{session?'Save your pavilion and pick it up on any device.':'Sign in to save and reopen your pavilion designs.'}</DialogDescription></DialogHeader>{!ready?<p>Connecting…</p>:!session?<form className="saved-form" onSubmit={authenticate}><label>Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" autoComplete={signup?'new-password':'current-password'} minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/></label><Button disabled={busy}>{busy?'Please wait…':signup?'Create account':'Sign in'}</Button><Button type="button" variant="ghost" onClick={()=>{setSignup(!signup);setMessage('')}}>{signup?'Already have an account? Sign in':'Create a design account'}</Button></form>:<><div className="account-row"><span>{session.user.email}</span><Button variant="ghost" size="sm" disabled={busy} onClick={signOut}>Sign out</Button></div><label className="save-name">Design name<input value={name} maxLength={120} onChange={e=>setName(e.target.value)}/></label><div className="save-actions"><Button disabled={busy} onClick={()=>save()}>{busy?'Saving…':saved?'Save changes':'Save current design'}</Button>{saved&&<Button variant="outline" disabled={busy} onClick={()=>save(true)}>Save a copy</Button>}</div><h3>Saved pavilions</h3>{loading?<p>Loading your designs…</p>:list.length?<div className="saved-list">{list.map(row=><button className="saved-row" key={row.id} disabled={busy} onClick={()=>load(row)}><FolderOpen size={20}/><span><strong>{row.name}</strong><small>{new Date(row.updated_at).toLocaleDateString()}</small></span><ChevronRight size={18}/></button>)}</div>:<p>No saved pavilions yet.</p>}</>}{message&&<p role="status" className="saved-message">{message}</p>}</DialogContent></Dialog>;
}
