const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),ts=require('typescript');
const root=path.resolve(__dirname,'..'),resolve=Module._resolveFilename;
Module._resolveFilename=function(id,...args){return resolve.call(this,id.startsWith('@/')?path.join(root,id.slice(2)):id,...args)};
for(const ext of ['.ts','.tsx'])require.extensions[ext]=(module,file)=>module._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText,file);
const {initialDesign,designSchema}=require('../components/pavilion/designer-model.ts');
const {furnitureBounds}=require('../components/pavilion/furniture-layout.ts');
const {readDraft,writeDraft}=require('../components/pavilion/local-draft.ts');
const {changeHistory}=require('../components/pavilion/design-history.ts');
const {decodeDesignHash,pavilionSummary,customerSchema}=require('../lib/pavilion-commerce.ts');
const {quoteEmbedPayload,notifyQuoteParent}=require('../lib/pavilion-embed.ts');
const {loadQuoteActivity}=require('../components/admin/quote-activity.ts');
const old={...initialDesign,furniture:'grill'};delete old.furnitureLayout;delete old.tv;
const migrated=designSchema.parse(old);assert.equal(migrated.furnitureLayout.grill.enabled,true);assert.equal(migrated.furnitureLayout.picnic.enabled,false);
const edited=designSchema.parse({...migrated,furnitureLayout:{...migrated.furnitureLayout,sectional:{enabled:true,x:10000,z:-10000,rotation:90}},tv:{enabled:true,corner:'br',height:8}});
assert.equal(edited.tv.height,6);assert.equal(edited.furnitureLayout.sectional.x,furnitureBounds(edited.config,'sectional',90).x);
assert.equal(edited.furnitureLayout.grill.enabled,true);
const shrunk=designSchema.parse({...edited,config:{...edited.config,width:12,length:16}});assert.ok(shrunk.furnitureLayout.sectional.x<=furnitureBounds(shrunk.config,'sectional',90).x);
assert.deepEqual(decodeDesignHash('#design='+btoa(encodeURIComponent(JSON.stringify(edited)))),edited);
let saved;const storage={getItem:()=>saved,setItem:(key,value)=>{saved=value}};writeDraft(storage,edited);assert.deepEqual(readDraft(storage),edited);saved='{invalid';assert.equal(readDraft(storage),null);
let history={present:initialDesign,past:[],future:[],group:null};history=changeHistory(history,{type:'set',value:edited,group:1});history=changeHistory(history,{type:'undo'});assert.deepEqual(history.present,initialDesign);history=changeHistory(history,{type:'redo'});assert.deepEqual(history.present,edited);
const customer=customerSchema.parse({name:'Offline',email:'test@example.invalid',phone:'12345',fulfillment:'pickup',address:'',notes:'',sendCopyToCustomer:false});
const payload=quoteEmbedPayload(edited,customer,pavilionSummary(edited),'offline');assert.equal(payload.customer.sendCopyToCustomer,false);assert.equal(payload.type,'ksm:quote-request');
const messages=[];global.window={parent:{postMessage:(...args)=>messages.push(args)},location:{}};global.document={referrer:'https://ksmloghomes.com/pavilions'};notifyQuoteParent(payload);assert.equal(messages[0][1],'https://ksmloghomes.com');assert.equal(messages[0][0].design,edited);
global.document.referrer='';notifyQuoteParent(payload);assert.equal(messages.length,1);global.window.parent=global.window;notifyQuoteParent(payload);assert.equal(messages.length,1);
(async()=>{
 const now=new Date('2026-09-17T18:00:00Z'),rows=Array.from({length:1205},(_,i)=>({id:String(i),created_at:'2026-09-17T12:00:00Z'})),ranges=[];
 const db={from:()=>({select:(fields,options)=>{if(options?.head)return Promise.resolve({count:1500,error:null});const query={gte:()=>query,lte:()=>query,order:()=>query,range:(a,b)=>{ranges.push([a,b]);return Promise.resolve({data:rows.slice(a,b+1),error:null})}};return query}})};
 const stats=await loadQuoteActivity(db,now);assert.equal(stats.total,1500);assert.equal(stats.last30,1205);assert.equal(stats.last7,1205);assert.equal(stats.days.length,30);assert.deepEqual(ranges,[[0,999],[1000,1999]]);
 console.log('Feature checks passed: legacy designs, combinations, placement bounds, TV height, shared links, drafts, undo/redo, email opt-out, scoped embed events, and paginated activity.');
})().catch(e=>{console.error(e);process.exitCode=1});
